# Generated by Django 5.2.8 on 2026-09-04 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_envoye',
            field=models.BooleanField(default=False, help_text="Indique si l'email associé à cette notification a été envoyé avec succès.", verbose_name='email envoyé'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'lu'], name='notificatio_utilisa_914765_idx'),
        ),
    ]
