# Generated by Django 5.2.8 on 2026-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_email_envoye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ECHEANCE_LOYER', 'Échéance de loyer'), ('FIN_CONTRAT', 'Fin de contrat'), ('RETARD_PAIEMENT', 'Retard de paiement'), ('NOUVELLE_RESERVATION', 'Nouvelle réservation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='type'),
        ),
    ]
