# Generated by Django 5.2.8 on 2026-09-16 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='lien'),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CONTRAT_CREE', 'Contrat créé'), ('PAIEMENT_VALIDE', 'Paiement validé'), ('ECHEANCE_PROCHE', 'Échéance proche'), ('PAIEMENT_EN_RETARD', 'Paiement en retard'), ('NOUVELLE_RESERVATION', 'Nouvelle réservation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='type'),
        ),
    ]
