# Generated by Django 5.2.8 on 2026-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options_remove_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
    ]
