# Generated by Django 5.2.8 on 2026-09-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0003_contrat_date_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField(help_text='Date à laquelle le paiement est attendu', verbose_name="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, help_text="Date effective du paiement (remplie lors de l'enregistrement)", null=True, verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant payé (doit correspondre au loyer du contrat, sauf paiement partiel)', max_digits=10, verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('MVOLA', 'Mvola'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('ESPECE', 'Espèce')], default='ESPECE', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, help_text='Obligatoire pour les paiements par Mobile Money', max_length=100, null=True, verbose_name='Référence de transaction')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('est_partiel', models.BooleanField(default=False, help_text='Cocher si le paiement ne couvre pas la totalité du loyer', verbose_name='Paiement partiel')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='contrats.contrat', verbose_name='Contrat associé')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiement',
                'ordering': ['-date_creation'],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gte', 0)), name='paiement_montant_positive')],
            },
        ),
    ]
