# Generated by Django 5.2.8 on 2026-09-06 08:01

import paiement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='fichier_quittance',
            field=models.FileField(blank=True, help_text='PDF généré automatiquement après validation du paiement', null=True, upload_to=paiement.models.quittance_upload_path, verbose_name='Fichier quittance'),
        ),
    ]
