# Generated by Django 5.2.8 on 2026-09-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_contrat_date_paiement'),
        ('paiement', '0002_paiement_fichier_quittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_attendu',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant attendu pour cette échéance (rempli automatiquement par l'échéancier)", max_digits=10, null=True, verbose_name='Montant attendu'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant effectivement payé pour cette échéance', max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('PARTIEL', 'Partiel'), ('EN_RETARD', 'En retard'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('contrat', 'date_echeance'), name='paiement_unique_contrat_echeance'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(condition=models.Q(('montant_attendu__gte', 0), ('montant_attendu__isnull', True), _connector='OR'), name='paiement_montant_attendu_positive'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(condition=models.Q(('montant_paye__gte', 0)), name='paiement_montant_paye_positive'),
        ),
    ]
