# Generated by Django 5.2.8 on 2026-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_echeancier_automatique'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_versement_partiel',
            field=models.DateField(blank=True, help_text='Date à laquelle le versement partiel a été effectué', null=True, verbose_name='Date du versement partiel'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='num_echeance',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Position de cette échéance dans l'échéancier (1 = première)", null=True, verbose_name="Numéro d'échéance"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='est_partiel',
            field=models.BooleanField(default=False, help_text='Cocher si le paiement ne couvre pas la totalité du montant attendu', verbose_name='Paiement partiel'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('MVOLA', 'Mvola'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('ESPECE', 'Espèce')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant payé (doit correspondre au montant attendu du contrat, sauf paiement partiel)', max_digits=10, verbose_name='Montant'),
        ),
    ]
