# Generated by Django 5.2.8 on 2026-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0004_paiement_achat_partiel_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant payé (doit correspondre au montant attendu du contrat, sauf paiement partiel)', max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_attendu',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant attendu pour cette échéance (rempli automatiquement par l'échéancier)", max_digits=15, null=True, verbose_name='Montant attendu'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant effectivement payé pour cette échéance', max_digits=15, verbose_name='Montant payé'),
        ),
    ]
