# Generated by Django 5.2.8 on 2026-09-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_paiement_max_digits_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_paiement_prevue',
            field=models.DateField(blank=True, editable=False, help_text='Date de paiement prévue générée automatiquement', null=True, verbose_name='Date de paiement prévue'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_echeance',
            field=models.DateField(editable=False, help_text='Date à laquelle le paiement est attendu', verbose_name="Date d'échéance"),
        ),
    ]
