# Generated by Django 5.2.8 on 2026-09-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0005_remove_contrat_contrat_statut_autorise_and_more'),
        ('paiement', '0006_paiement_date_paiement_prevue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_echeance',
            field=models.DateField(db_index=True, editable=False, help_text='Date à laquelle le paiement est attendu', verbose_name="Date d'échéance"),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['contrat', 'date_echeance'], name='paiement_contrat_fe956d_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut', 'date_echeance'], name='paiement_statut_e11c6b_idx'),
        ),
    ]
