apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: immobilier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: didierherlin/login-page-immobilier:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            # Assurer que le conteneur démarre et a les mêmes variables d'environnement au cas où (standalone mode)
            - name: NEXT_PUBLIC_API_URL
              value: "http://immobilier.local/api"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
