# Generated by Django 5.2.8 on 2026-09-01 11:16

import datetime
import django.core.validators
import django.db.models.deletion
import utilisateur.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 1, 11, 14, 54, 310523, tzinfo=datetime.timezone.utc), verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenoms',
            field=models.CharField(default='Inconnu', max_length=150, verbose_name='prénoms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reset_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil (optionnel). Formats acceptés : JPG, PNG, GIF', null=True, upload_to=utilisateur.models.photo_profil_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='photo de profil'),
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='locataires/pieces_identite/', verbose_name="pièce d'identité")),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_locataire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
        ),
    ]
