# Generated by Django 5.2.8 on 2026-09-05 07:51

import bien.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('type', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('LOCAL_COMMERCIAL', 'Local commercial'), ('TERRAIN', 'Terrain')], max_length=20, verbose_name='type de bien')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse')),
                ('surface', models.FloatField(validators=[bien.validators.PositiveValueValidator('La surface ne peut pas être négative.')], verbose_name='surface (m²)')),
                ('nombre_pieces', models.IntegerField(validators=[bien.validators.PositiveValueValidator('Le nombre de pièces ne peut pas être négatif.')], verbose_name='nombre de pièces')),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[bien.validators.PositiveValueValidator('Le loyer mensuel ne peut pas être négatif.')], verbose_name='loyer mensuel')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('EN_TRAVAUX', 'En travaux')], default='DISPONIBLE', max_length=20, verbose_name='statut')),
                ('photos', models.JSONField(blank=True, default=list, null=True, validators=[bien.validators.PhotosListValidator()], verbose_name='photos')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='utilisateur.proprietaire', verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Biens',
                'ordering': ['-id'],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('surface__gte', 0)), name='bien_surface_positive'),
                    models.CheckConstraint(condition=models.Q(('nombre_pieces__gte', 0)), name='bien_nombre_pieces_positive'),
                    # 👇 nom corrigé
                    models.CheckConstraint(condition=models.Q(('loyer_mensuel__gte', 0)), name='bien_loyer_positive')
                ],
            },
        ),
    ]