# Generated by Django 5.2.8 on 2026-09-05 13:13

import bien.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0001_initial'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bien',
            name='bien_nombre_pieces_positive',
        ),
        migrations.RemoveConstraint(
            model_name='bien',
            name='bien_loyer_positive',
        ),
        migrations.AddField(
            model_name='bien',
            name='mode_transaction',
            field=models.CharField(choices=[('LOCATION', 'Location'), ('VENTE', 'Vente')], default='LOCATION', max_length=20, verbose_name='mode de transaction'),
        ),
        migrations.AddField(
            model_name='bien',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[bien.validators.PositiveValueValidator('Le prix ne peut pas être négatif.')], verbose_name='prix de vente'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='loyer_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[bien.validators.PositiveValueValidator('Le loyer mensuel ne peut pas être négatif.')], verbose_name='loyer mensuel'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='nombre_pieces',
            field=models.IntegerField(blank=True, null=True, validators=[bien.validators.PositiveValueValidator('Le nombre de pièces ne peut pas être négatif.')], verbose_name='nombre de pièces'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('VENDU', 'Vendu'), ('EN_TRAVAUX', 'En travaux')], default='DISPONIBLE', max_length=20, verbose_name='statut'),
        ),
        migrations.AddConstraint(
            model_name='bien',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_pieces__gte', 0), ('nombre_pieces__isnull', True), _connector='OR'), name='bien_nombre_pieces_positive'),
        ),
        migrations.AddConstraint(
            model_name='bien',
            constraint=models.CheckConstraint(condition=models.Q(('loyer_mensuel__gte', 0), ('loyer_mensuel__isnull', True), _connector='OR'), name='bien_loyer_positive'),
        ),
        migrations.AddConstraint(
            model_name='bien',
            constraint=models.CheckConstraint(condition=models.Q(('prix__gte', 0), ('prix__isnull', True), _connector='OR'), name='bien_prix_positive'),
        ),
        migrations.AddConstraint(
            model_name='bien',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode_transaction', 'LOCATION'), ('loyer_mensuel__isnull', False), ('prix__isnull', True)), models.Q(('mode_transaction', 'VENTE'), ('prix__isnull', False), ('loyer_mensuel__isnull', True)), _connector='OR'), name='bien_coherence_location_vente'),
        ),
        migrations.AddConstraint(
            model_name='bien',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'TERRAIN'), ('nombre_pieces__isnull', True)), models.Q(('type__in', ['APPARTEMENT', 'MAISON', 'LOCAL_COMMERCIAL']), ('nombre_pieces__isnull', False)), _connector='OR'), name='bien_terrain_pas_pieces'),
        ),
    ]
