# Generated by Django 5.2.8 on 2026-09-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0003_fix_terrain_nombre_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('VENDU', 'Vendu'), ('EN_TRAVAUX', 'En travaux'), ('RESERVE', 'Réservé')], default='DISPONIBLE', max_length=20, verbose_name='statut'),
        ),
    ]
