# Generated by Django 5.2.8 on 2026-09-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0004_alter_bien_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='mode_transaction',
            field=models.CharField(choices=[('LOCATION', 'Location'), ('VENTE', 'Vente')], db_index=True, default='LOCATION', max_length=20, verbose_name='mode de transaction'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('VENDU', 'Vendu'), ('EN_TRAVAUX', 'En travaux'), ('RESERVE', 'Réservé')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type',
            field=models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('LOCAL_COMMERCIAL', 'Local commercial'), ('TERRAIN', 'Terrain')], db_index=True, max_length=20, verbose_name='type de bien'),
        ),
    ]
