# Generated by Django 5.2.8 on 2026-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0005_alter_bien_mode_transaction_alter_bien_statut_and_more'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['statut', 'type', 'mode_transaction'], name='idx_bien_recherche'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['proprietaire'], name='idx_bien_proprietaire'),
        ),
    ]
