# Generated by Django 5.2.8 on 2026-09-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bien', '0004_alter_bien_statut'),
        ('contrats', '0005_remove_contrat_contrat_statut_autorise_and_more'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, default='', help_text='Commentaire ou message du locataire.', verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('type_reservation', models.CharField(choices=[('LOCATION', 'Location'), ('ACHAT', 'Achat')], max_length=20, verbose_name='type de réservation')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEE', 'Traitée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('reponse_admin', models.TextField(blank=True, default='', help_text="Réponse de l'admin ou de l'agent immobilier au locataire.", verbose_name="réponse de l'administrateur")),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='bien.bien', verbose_name='bien concerné')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='contrats.contrat', verbose_name='contrat associé')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='utilisateur.locataire', verbose_name='locataire')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
