# Generated by Django 5.2.8 on 2026-09-05 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bien', '0001_initial'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Loyer mensuel')),
                ('depot_garantie', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dépôt de garantie')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('RESILIE', 'Résilié'), ('TERMINE', 'Terminé')], db_index=True, default='ACTIF', max_length=20, verbose_name='Statut')),
                ('document_pdf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chemin du document PDF')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='bien.bien', verbose_name='Bien loué')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='utilisateur.locataire', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'db_table': 'contrat',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['bien', 'statut'], name='idx_contrat_bien_statut')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='rg12_date_fin_gt_date_debut'), models.CheckConstraint(condition=models.Q(('loyer__gte', 0)), name='ck_contrat_loyer_positif'), models.CheckConstraint(condition=models.Q(('depot_garantie__gte', 0)), name='ck_contrat_depot_garantie_positif'), models.UniqueConstraint(condition=models.Q(('statut', 'ACTIF')), fields=('bien',), name='rg13_un_seul_contrat_actif_par_bien')],
            },
        ),
    ]
