# Generated by Django 5.2.8 on 2026-09-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0002_remove_bien_bien_nombre_pieces_positive_and_more'),
        ('contrats', '0001_initial'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contrat',
            name='rg12_date_fin_gt_date_debut',
        ),
        migrations.RemoveConstraint(
            model_name='contrat',
            name='ck_contrat_loyer_positif',
        ),
        migrations.RemoveConstraint(
            model_name='contrat',
            name='ck_contrat_depot_garantie_positif',
        ),
        migrations.RemoveIndex(
            model_name='contrat',
            name='idx_contrat_bien_statut',
        ),
        migrations.AddField(
            model_name='contrat',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix de vente'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('LOCATION', 'Location'), ('ACHAT', 'Achat')], default='LOCATION', max_length=20, verbose_name='type de contrat'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='bien.bien', verbose_name='Bien concerné'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dépôt de garantie'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='utilisateur.locataire', verbose_name='Locataire / Acheteur'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='loyer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Loyer mensuel'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('RESILIE', 'Résilié'), ('TERMINE', 'Terminé'), ('VENDU', 'Vendu')], db_index=True, default='ACTIF', max_length=20, verbose_name='statut'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_contrat', 'LOCATION'), ('loyer__isnull', False), ('depot_garantie__isnull', False), ('prix__isnull', True)), models.Q(('type_contrat', 'ACHAT'), ('prix__isnull', False), ('loyer__isnull', True), ('depot_garantie__isnull', True)), _connector='OR'), name='contrat_coherence_location_achat'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_contrat', 'LOCATION'), ('statut__in', ['ACTIF', 'RESILIE', 'TERMINE'])), models.Q(('type_contrat', 'ACHAT'), ('statut__in', ['ACTIF', 'VENDU'])), _connector='OR'), name='contrat_statut_autorise'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_contrat', 'LOCATION'), ('date_fin__isnull', False), ('date_fin__gt', models.F('date_debut'))), models.Q(('type_contrat', 'ACHAT'), ('date_fin__isnull', True)), _connector='OR'), name='contrat_dates_location'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(('loyer__gte', 0), ('loyer__isnull', True), _connector='OR'), name='contrat_loyer_positive'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(('depot_garantie__gte', 0), ('depot_garantie__isnull', True), _connector='OR'), name='contrat_depot_positive'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(('prix__gte', 0), ('prix__isnull', True), _connector='OR'), name='contrat_prix_positive'),
        ),
    ]
