# Generated by Django 5.2.8 on 2026-09-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_remove_contrat_rg12_date_fin_gt_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date_paiement',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Date de paiement'),
        ),
    ]
