# Generated by Django 5.2.8 on 2026-09-10 07:08

from django.db import migrations, models


def set_default_type_paiement(apps, schema_editor):
    Contrat = apps.get_model('contrats', 'Contrat')
    Contrat.objects.filter(type_contrat='ACHAT').update(type_paiement_achat='TOTALITE')

class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0004_alter_bien_statut'),
        ('contrats', '0003_contrat_date_paiement'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contrat',
            name='contrat_coherence_location_achat',
        ),
        migrations.RemoveConstraint(
            model_name='contrat',
            name='contrat_dates_location',
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_paiement_achat',
            field=models.CharField(blank=True, choices=[('TOTALITE', 'Totalité'), ('PARTIEL', 'Partiel')], max_length=20, null=True, verbose_name='type de paiement (achat)'),
        ),
        migrations.RunPython(set_default_type_paiement, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contrat',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_contrat', 'LOCATION'), ('loyer__isnull', False), ('depot_garantie__isnull', False), ('prix__isnull', True), ('type_paiement_achat__isnull', True)), models.Q(('type_contrat', 'ACHAT'), ('prix__isnull', False), ('loyer__isnull', True), ('depot_garantie__isnull', True), ('type_paiement_achat__isnull', False)), _connector='OR'), name='contrat_coherence_location_achat'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_contrat', 'LOCATION'), ('date_fin__isnull', False), ('date_debut__isnull', False), ('date_fin__gt', models.F('date_debut'))), models.Q(('type_contrat', 'ACHAT'), ('date_fin__isnull', True)), _connector='OR'), name='contrat_dates_location'),
        ),
    ]
