# Generated by Django 5.2.8 on 2026-09-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0004_alter_bien_statut'),
        ('contrats', '0004_remove_contrat_contrat_coherence_location_achat_and_more'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contrat',
            name='contrat_statut_autorise',
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('RESERVE', 'Réservé'), ('ACTIF', 'Actif'), ('RESILIE', 'Résilié'), ('TERMINE', 'Terminé'), ('VENDU', 'Vendu')], db_index=True, default='ACTIF', max_length=20, verbose_name='statut'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_contrat', 'LOCATION'), ('statut__in', ['ACTIF', 'RESILIE', 'TERMINE'])), models.Q(('type_contrat', 'ACHAT'), ('statut__in', ['RESERVE', 'ACTIF', 'VENDU'])), _connector='OR'), name='contrat_statut_autorise'),
        ),
    ]
