sonar.projectKey=gestion-immobiliere
sonar.projectName=Gestion Immobiliere Backend
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py

# Exclure les fichiers qui ne necessitent pas d'analyse qualité
sonar.exclusions=**/migrations/**,manage.py,**/venv/**,**/.venv/**,**/tests.py,**/test_*.py,configuration/settings.py

# Integration du rapport de couverture genéré par coverage.py
# sonar-scanner cherchera ce fichier XML pour remonter la couverture dans SonarQube
sonar.python.coverage.reportPaths=coverage.xml

# Encodage
sonar.sourceEncoding=UTF-8
