from django.urls import reverse
from rest_framework.test import APITestCase
from rest_framework import status
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from utilisateur.models import Utilisateur, Locataire, Proprietaire
from bien.models import Bien
from contrats.models import Contrat
from paiement.models import Paiement

class ReportingStatsTests(APITestCase):
    def setUp(self):
        # Admin
        self.admin = Utilisateur.objects.create_user(email='admin@test.com', password='password123', role=Utilisateur.Role.ADMIN)
        # Agent
        self.agent = Utilisateur.objects.create_user(email='agent@test.com', password='password123', role=Utilisateur.Role.AGENT)
        # Proprio
        self.proprio_user = Utilisateur.objects.create_user(email='proprio@test.com', password='password123', role=Utilisateur.Role.PROPRIETAIRE)
        self.proprio = Proprietaire.objects.create(user=self.proprio_user)
        # Locataire
        self.loc_user = Utilisateur.objects.create_user(email='loc@test.com', password='password123', role=Utilisateur.Role.LOCATAIRE)
        self.locataire = Locataire.objects.create(user=self.loc_user)

        # Bien
        self.bien = Bien.objects.create(
            proprietaire=self.proprio,
            titre="Bien test",
            type="APPARTEMENT",
            mode_transaction="LOCATION",
            adresse="Paris",
            surface=50,
            nombre_pieces=2,
            loyer_mensuel=1000,
            statut="DISPONIBLE"
        )
        self.bien_dispo = Bien.objects.create(
            proprietaire=self.proprio,
            titre="Bien dispo",
            type="APPARTEMENT",
            mode_transaction="LOCATION",
            adresse="Paris",
            surface=50,
            nombre_pieces=2,
            loyer_mensuel=1000,
            statut="DISPONIBLE"
        )
        
        # Contrat
        self.contrat = Contrat.objects.create(
            bien=self.bien,
            locataire=self.locataire,
            type_contrat="LOCATION",
            date_debut=timezone.now().date(),
            date_fin=timezone.now().date() + relativedelta(years=1),
            loyer=1000,
            depot_garantie=1000,
            statut="ACTIF"
        )
        
        # Paiement generated by echeancier
        self.paiement = Paiement.objects.filter(contrat=self.contrat).first()
        if self.paiement:
            self.paiement.statut = "PAYE"
            self.paiement.montant_paye = 1000
            self.paiement.save(update_fields=["statut", "montant_paye"])
        
        self.url = reverse('reporting-stats')

    def test_stats_admin(self):
        self.client.force_authenticate(user=self.admin)
        response = self.client.get(self.url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['biens']['total'], 2)
        self.assertEqual(response.data['contrats']['actifs'], 1)
        self.assertEqual(response.data['paiements']['payes'], 1)
        self.assertEqual(response.data['paiements']['total'], 12)
        self.assertIn('total_users', response.data['users'])

    def test_stats_proprietaire(self):
        self.client.force_authenticate(user=self.proprio_user)
        response = self.client.get(self.url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['biens']['total'], 2)
        self.assertEqual(response.data['contrats']['total'], 1)
        self.assertEqual(response.data['paiements']['total'], 12)

    def test_stats_locataire(self):
        self.client.force_authenticate(user=self.loc_user)
        response = self.client.get(self.url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        # Locataire only sees AVAILABLE biens and THEIR contracts
        self.assertEqual(response.data['biens']['total'], 1)
        self.assertEqual(response.data['contrats']['total'], 1)
        self.assertEqual(response.data['paiements']['total'], 12)
        self.assertEqual(response.data['users'], {}) # No user stats for locataire

    def test_unauthenticated(self):
        response = self.client.get(self.url)
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
